"""Initial accounts sessions and finance schema

Revision ID: 202610010001
Revises: 
"""
from alembic import op
import sqlalchemy as sa

revision = '202610010001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=False),
    sa.Column('monthly_budget_cents', sa.BigInteger(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('length(display_name) BETWEEN 2 AND 60', name='ck_user_name'),
    sa.CheckConstraint('monthly_budget_cents >= 0 AND monthly_budget_cents <= 100000000000000', name='ck_user_budget'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auth_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=8), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('consumed_at', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("purpose IN ('signup','recovery')", name='ck_auth_code_purpose'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('auth_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_codes_user_id'), ['user_id'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_hash', sa.String(length=64), nullable=False),
    sa.Column('recovery', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('revoked_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_hash')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('categories',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=30), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('monthly_limit_cents', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("id IN ('food','transport','study','leisure','other')", name='ck_category_id'),
    sa.CheckConstraint('monthly_limit_cents >= 0 AND monthly_limit_cents <= 100000000000000', name='ck_category_limit'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=16), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('payment_method', sa.String(length=4), nullable=False),
    sa.Column('note', sa.String(length=120), nullable=False),
    sa.Column('occurred_at', sa.String(length=35), nullable=False),
    sa.Column('created_at', sa.String(length=24), nullable=False),
    sa.CheckConstraint("payment_method IN ('card','cash')", name='ck_transaction_payment'),
    sa.CheckConstraint('amount_cents > 0 AND amount_cents <= 100000000000000', name='ck_transaction_amount'),
    sa.CheckConstraint('length(note) <= 120', name='ck_transaction_note'),
    sa.ForeignKeyConstraint(['user_id', 'category_id'], ['categories.user_id', 'categories.id'], name='fk_transaction_owned_category', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))

    op.drop_table('transactions')
    op.drop_table('categories')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('auth_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_codes_user_id'))

    op.drop_table('auth_codes')
    op.drop_table('users')
    # ### end Alembic commands ###
